serviceAccountName: sloop
name: sloop
replicas: 1
image:
  # for now, user needs to set their own imag tag,for example:test-20191009
  tag: latest
  # for now, user needs to set their own image
  repository: some.image/sloop
persistentVolume:
## If defined it will specify the storageClass for the statefulSet
## If undefined it will use the cluster default (typically gp2 on AWS, standard on GKE)
#  storageClass: 
  size: 10Gi
resources: {}
