apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  name: {{ .Values.name }}
spec:
  ports:
  - name: sloop-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: sloop
